package Gerente;

import VIew.Frame1;
import VIew.Funcionario.*;
import com.sun.security.ntlm.Client;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author waldirene
 */
public class Gerente extends javax.swing.JFrame {

    /**
     * Creates new form Funcionario
     */
    public Gerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenuItem();
        servico = new javax.swing.JMenuItem();
        produto = new javax.swing.JMenuItem();
        fornecedor = new javax.swing.JMenuItem();
        registro = new javax.swing.JMenuItem();
        agendar = new javax.swing.JMenu();
        agenda = new javax.swing.JMenuItem();
        consultar = new javax.swing.JMenu();
        consultar_p = new javax.swing.JMenuItem();
        estoque = new javax.swing.JMenuItem();
        registro_produto = new javax.swing.JMenuItem();
        consultar_Cliente = new javax.swing.JMenu();
        c_cliente = new javax.swing.JMenuItem();
        c_servico = new javax.swing.JMenuItem();
        c_produto = new javax.swing.JMenuItem();
        c_agenda = new javax.swing.JMenuItem();
        c_estoque = new javax.swing.JMenuItem();
        c_fucionario = new javax.swing.JMenuItem();
        c_venda = new javax.swing.JMenuItem();
        c_compra = new javax.swing.JMenuItem();
        c_fornecedor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        alterar_cliente = new javax.swing.JMenuItem();
        alterar_servico = new javax.swing.JMenuItem();
        alterar_funcionario = new javax.swing.JMenuItem();
        alterar_estoque = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        deletar_cliente = new javax.swing.JMenuItem();
        deletar_servico = new javax.swing.JMenuItem();
        deletar_cliente1 = new javax.swing.JMenuItem();
        deletar_cliente2 = new javax.swing.JMenuItem();
        deletar_fornecedor = new javax.swing.JMenuItem();
        deletar_funcionario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        voltar = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do Gerente");
        setFocusTraversalPolicyProvider(true);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon("/home/waldirene/Imagens/Webcam/dicas-de-maquiagem-para-mulheres-negras.jpg")); // NOI18N
        jLabel19.setText("Salão Seduction: prazer de ser bonita");

        jMenuBar1.setBackground(new java.awt.Color(50, 49, 47));

        jMenu1.setText("Cadastrar");

        cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.InputEvent.ALT_MASK));
        cliente.setForeground(new java.awt.Color(189, 0, 0));
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenu1.add(cliente);

        venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.ALT_MASK));
        venda.setForeground(new java.awt.Color(167, 2, 2));
        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        jMenu1.add(venda);

        funcionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        funcionario.setForeground(new java.awt.Color(167, 2, 2));
        funcionario.setText("Funcionário");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        jMenu1.add(funcionario);

        servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK));
        servico.setForeground(new java.awt.Color(167, 2, 2));
        servico.setText("Serviço");
        servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoActionPerformed(evt);
            }
        });
        jMenu1.add(servico);

        produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        produto.setForeground(new java.awt.Color(167, 2, 2));
        produto.setText("Produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        jMenu1.add(produto);

        fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fornecedor.setForeground(new java.awt.Color(167, 2, 2));
        fornecedor.setText("Fornecedor");
        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(fornecedor);

        registro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        registro.setForeground(new java.awt.Color(167, 2, 2));
        registro.setText("Registro de Produto");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jMenu1.add(registro);

        jMenuBar1.add(jMenu1);

        agendar.setText("Serviço");

        agenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        agenda.setForeground(new java.awt.Color(196, 14, 14));
        agenda.setText("Agendar");
        agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaActionPerformed(evt);
            }
        });
        agendar.add(agenda);

        jMenuBar1.add(agendar);

        consultar.setText("Produto");

        consultar_p.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        consultar_p.setForeground(new java.awt.Color(204, 1, 1));
        consultar_p.setText("Consultar");
        consultar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_pActionPerformed(evt);
            }
        });
        consultar.add(consultar_p);

        estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        estoque.setForeground(new java.awt.Color(204, 1, 1));
        estoque.setText("Inserir Produto no estoque");
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        consultar.add(estoque);

        registro_produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        registro_produto.setForeground(new java.awt.Color(204, 1, 1));
        registro_produto.setText("Registro de Produto");
        registro_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_produtoActionPerformed(evt);
            }
        });
        consultar.add(registro_produto);

        jMenuBar1.add(consultar);

        consultar_Cliente.setText("Consultar");

        c_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        c_cliente.setForeground(new java.awt.Color(224, 11, 11));
        c_cliente.setText("Cliente");
        c_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_clienteActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_cliente);

        c_servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        c_servico.setForeground(new java.awt.Color(204, 1, 1));
        c_servico.setText("Serviço");
        c_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_servicoActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_servico);

        c_produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        c_produto.setForeground(new java.awt.Color(203, 3, 3));
        c_produto.setText("Produto e Registro");
        c_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_produtoActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_produto);

        c_agenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        c_agenda.setForeground(new java.awt.Color(217, 2, 2));
        c_agenda.setText("Agenda");
        c_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_agendaActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_agenda);

        c_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        c_estoque.setForeground(new java.awt.Color(217, 26, 26));
        c_estoque.setText("Estoque");
        c_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_estoqueActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_estoque);

        c_fucionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        c_fucionario.setForeground(new java.awt.Color(217, 26, 26));
        c_fucionario.setText("Funcionário");
        c_fucionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_fucionarioActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_fucionario);

        c_venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        c_venda.setForeground(new java.awt.Color(217, 26, 26));
        c_venda.setText("Venda");
        c_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_vendaActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_venda);

        c_compra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        c_compra.setForeground(new java.awt.Color(217, 26, 26));
        c_compra.setText("Compra");
        c_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_compraActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_compra);

        c_fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        c_fornecedor.setForeground(new java.awt.Color(217, 26, 26));
        c_fornecedor.setText("Fornecedor");
        c_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_fornecedorActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_fornecedor);

        jMenuBar1.add(consultar_Cliente);

        jMenu5.setText("Alterar ");

        alterar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        alterar_cliente.setForeground(new java.awt.Color(152, 1, 1));
        alterar_cliente.setText("Alterar Cliente");
        alterar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_clienteActionPerformed(evt);
            }
        });
        jMenu5.add(alterar_cliente);

        alterar_servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        alterar_servico.setForeground(new java.awt.Color(161, 0, 0));
        alterar_servico.setText("Alterar Agenda");
        alterar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_servicoActionPerformed(evt);
            }
        });
        jMenu5.add(alterar_servico);

        alterar_funcionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        alterar_funcionario.setForeground(new java.awt.Color(161, 0, 0));
        alterar_funcionario.setText("Alterar Funcionário");
        alterar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_funcionarioActionPerformed(evt);
            }
        });
        jMenu5.add(alterar_funcionario);

        alterar_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        alterar_estoque.setForeground(new java.awt.Color(161, 0, 0));
        alterar_estoque.setText("Alterar Estoque");
        alterar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_estoqueActionPerformed(evt);
            }
        });
        jMenu5.add(alterar_estoque);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Deletar");

        deletar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        deletar_cliente.setForeground(new java.awt.Color(160, 1, 1));
        deletar_cliente.setText("Deletar Cliente");
        deletar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_clienteActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_cliente);

        deletar_servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.ALT_MASK));
        deletar_servico.setForeground(new java.awt.Color(144, 0, 0));
        deletar_servico.setText("Deletar Serviço");
        deletar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_servicoActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_servico);

        deletar_cliente1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.ALT_MASK));
        deletar_cliente1.setForeground(new java.awt.Color(160, 1, 1));
        deletar_cliente1.setText("Deletar Venda");
        deletar_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_cliente1ActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_cliente1);

        deletar_cliente2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.ALT_MASK));
        deletar_cliente2.setForeground(new java.awt.Color(160, 1, 1));
        deletar_cliente2.setText("Deletar Produto e Registro");
        deletar_cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_cliente2ActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_cliente2);

        deletar_fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        deletar_fornecedor.setForeground(new java.awt.Color(160, 1, 1));
        deletar_fornecedor.setText("Deletar Fornecedor");
        deletar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_fornecedorActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_fornecedor);

        deletar_funcionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.CTRL_MASK));
        deletar_funcionario.setForeground(new java.awt.Color(160, 1, 1));
        deletar_funcionario.setText("Deletar Funcionário");
        deletar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_funcionarioActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_funcionario);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setForeground(new java.awt.Color(161, 0, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setForeground(new java.awt.Color(143, 1, 1));
        jMenuItem2.setText("Ajuda");
        jMenu3.add(jMenuItem2);

        voltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        voltar.setForeground(new java.awt.Color(161, 0, 0));
        voltar.setText("Voltar a tela de login");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jMenu3.add(voltar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 356, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_servicoActionPerformed
        // TODO add your handling code here:
        
        
        new Consulta_ServicoG().setVisible(true);
        
    }//GEN-LAST:event_c_servicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        
       
    new Cliente().setVisible(true);
         
    }//GEN-LAST:event_clienteActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
  
        new Venda().setVisible(true);
        
    }//GEN-LAST:event_vendaActionPerformed

    private void consultar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_pActionPerformed
        // TODO add your handling code here:
        
        new Consultar_ProdutosG().setVisible(true);
    }//GEN-LAST:event_consultar_pActionPerformed

    private void c_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_clienteActionPerformed
        
        new Consulta_ClienteG().setVisible(true);
        
    }//GEN-LAST:event_c_clienteActionPerformed

    private void c_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_produtoActionPerformed
        // TODO add your handling code here:
        
        new Consultar_ProdutosG().setVisible(true);
        
    }//GEN-LAST:event_c_produtoActionPerformed

    private void alterar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_servicoActionPerformed
        // TODO add your handling code here:
         new Alterar_AgendaG().setVisible(true);
        
    }//GEN-LAST:event_alterar_servicoActionPerformed

    private void alterar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_clienteActionPerformed
        // TODO add your handling code here:
        
      
       
    }//GEN-LAST:event_alterar_clienteActionPerformed

    private void agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaActionPerformed
        // TODO add your handling code here:
        
        new Agenda().setVisible(true);
        
    }//GEN-LAST:event_agendaActionPerformed

    private void c_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_agendaActionPerformed
        // TODO add your handling code here:
        
        new Consultar_AgendaG().setVisible(true);
    }//GEN-LAST:event_c_agendaActionPerformed

    private void c_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_estoqueActionPerformed
        // TODO add your handling code here:
        new Consultar_EstoqueG().setVisible(true);
    }//GEN-LAST:event_c_estoqueActionPerformed

    private void deletar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_clienteActionPerformed
        // TODO add your handling code here:
        new Deletar_Cliente().setVisible(true);
    }//GEN-LAST:event_deletar_clienteActionPerformed

    private void deletar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_servicoActionPerformed
        // TODO add your handling code here:
        
        new Deletar_Servico().setVisible(true);
    }//GEN-LAST:event_deletar_servicoActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        new Funcionario().setVisible(true);
        
    }//GEN-LAST:event_funcionarioActionPerformed

    private void servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoActionPerformed
        // TODO add your handling code here:
        
        new Servico().setVisible(true);
                
    }//GEN-LAST:event_servicoActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
        new Produto().setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void c_fucionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_fucionarioActionPerformed
        // TODO add your handling code here:
        
        new Consultar_FuncionaioG().setVisible(true);
        
    }//GEN-LAST:event_c_fucionarioActionPerformed

    private void c_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_vendaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_c_vendaActionPerformed

    private void c_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_compraActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        // TODO add your handling code here:
        new Estoque().setVisible(true);
    }//GEN-LAST:event_estoqueActionPerformed

    private void registro_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_produtoActionPerformed
        // TODO add your handling code here:
        new Registro_Produto().setVisible(true);
    }//GEN-LAST:event_registro_produtoActionPerformed

    private void deletar_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_cliente1ActionPerformed
        // TODO add your handling code here:
        
        new Deletar_Venda().setVisible(true);
    }//GEN-LAST:event_deletar_cliente1ActionPerformed

    private void deletar_cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_cliente2ActionPerformed
        // TODO add your handling code here:
        new Deletar_Produto().setVisible(true);
    }//GEN-LAST:event_deletar_cliente2ActionPerformed

    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        // TODO add your handling code here:
        new Fornecedor().setVisible(true);
    }//GEN-LAST:event_fornecedorActionPerformed

    private void c_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_fornecedorActionPerformed
        // TODO add your handling code here:
        
        new Consultar_Forncedor().setVisible(true);
    }//GEN-LAST:event_c_fornecedorActionPerformed

    private void deletar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_fornecedorActionPerformed
        // TODO add your handling code here:
        new Deletar_Fornecedor().setVisible(true);
    }//GEN-LAST:event_deletar_fornecedorActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        new Registro_Produto().setVisible(true);
    }//GEN-LAST:event_registroActionPerformed

    private void alterar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_funcionarioActionPerformed
        // TODO add your handling code here:
        new Alterar_Funcionario().setVisible(true);
        
        
    }//GEN-LAST:event_alterar_funcionarioActionPerformed

    private void deletar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_funcionarioActionPerformed
        // TODO add your handling code here:
        new Deletar_Funcionario().setVisible(true);
    }//GEN-LAST:event_deletar_funcionarioActionPerformed

    private void alterar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_estoqueActionPerformed
        // TODO add your handling code here:
        new Alterar_Estoque().setVisible(true);
    }//GEN-LAST:event_alterar_estoqueActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        
        new Frame1().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agenda;
    private javax.swing.JMenu agendar;
    private javax.swing.JMenuItem alterar_cliente;
    private javax.swing.JMenuItem alterar_estoque;
    private javax.swing.JMenuItem alterar_funcionario;
    private javax.swing.JMenuItem alterar_servico;
    private javax.swing.JMenuItem c_agenda;
    private javax.swing.JMenuItem c_cliente;
    private javax.swing.JMenuItem c_compra;
    private javax.swing.JMenuItem c_estoque;
    private javax.swing.JMenuItem c_fornecedor;
    private javax.swing.JMenuItem c_fucionario;
    private javax.swing.JMenuItem c_produto;
    private javax.swing.JMenuItem c_servico;
    private javax.swing.JMenuItem c_venda;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenu consultar;
    private javax.swing.JMenu consultar_Cliente;
    private javax.swing.JMenuItem consultar_p;
    private javax.swing.JMenuItem deletar_cliente;
    private javax.swing.JMenuItem deletar_cliente1;
    private javax.swing.JMenuItem deletar_cliente2;
    private javax.swing.JMenuItem deletar_fornecedor;
    private javax.swing.JMenuItem deletar_funcionario;
    private javax.swing.JMenuItem deletar_servico;
    private javax.swing.JMenuItem estoque;
    private javax.swing.JMenuItem fornecedor;
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem registro;
    private javax.swing.JMenuItem registro_produto;
    private javax.swing.JMenuItem servico;
    private javax.swing.JMenuItem venda;
    private javax.swing.JMenuItem voltar;
    // End of variables declaration//GEN-END:variables
}
