package VIew.Funcionario;

import VIew.Frame1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author waldirene
 */
public class Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Funcionario
     */
    public Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agenda = new javax.swing.JMenuItem();
        consultar = new javax.swing.JMenu();
        consultar_p = new javax.swing.JMenuItem();
        consultar_Cliente = new javax.swing.JMenu();
        c_cliente = new javax.swing.JMenuItem();
        comsultar_servico = new javax.swing.JMenuItem();
        consultar_produto = new javax.swing.JMenuItem();
        c_agenda = new javax.swing.JMenuItem();
        consultar_estoque = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        alterar_cliente = new javax.swing.JMenuItem();
        agenda_servico = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        deletar_cliente = new javax.swing.JMenuItem();
        deletar_agenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        voltar = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do Funcionário");
        setFocusTraversalPolicyProvider(true);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon("/home/waldirene/Imagens/Webcam/red-lips-3-672x372_zps3998d24c.jpg")); // NOI18N
        jLabel19.setText("Salão Saduction: O prazer de ser bonita");

        jMenuBar1.setBackground(new java.awt.Color(50, 49, 47));

        jMenu1.setText("Cadastrar");

        cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.InputEvent.ALT_MASK));
        cliente.setForeground(new java.awt.Color(189, 0, 0));
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenu1.add(cliente);

        venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.ALT_MASK));
        venda.setForeground(new java.awt.Color(167, 2, 2));
        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        jMenu1.add(venda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Serviço");

        agenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK));
        agenda.setForeground(new java.awt.Color(196, 14, 14));
        agenda.setText("Agendar");
        agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaActionPerformed(evt);
            }
        });
        jMenu2.add(agenda);

        jMenuBar1.add(jMenu2);

        consultar.setText("Produto");

        consultar_p.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        consultar_p.setForeground(new java.awt.Color(204, 1, 1));
        consultar_p.setText("Consultar");
        consultar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_pActionPerformed(evt);
            }
        });
        consultar.add(consultar_p);

        jMenuBar1.add(consultar);

        consultar_Cliente.setText("Consultar");

        c_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        c_cliente.setForeground(new java.awt.Color(224, 11, 11));
        c_cliente.setText("Cliente");
        c_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_clienteActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_cliente);

        comsultar_servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        comsultar_servico.setForeground(new java.awt.Color(204, 1, 1));
        comsultar_servico.setText("Serviço");
        comsultar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comsultar_servicoActionPerformed(evt);
            }
        });
        consultar_Cliente.add(comsultar_servico);

        consultar_produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        consultar_produto.setForeground(new java.awt.Color(203, 3, 3));
        consultar_produto.setText("Produto");
        consultar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_produtoActionPerformed(evt);
            }
        });
        consultar_Cliente.add(consultar_produto);

        c_agenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        c_agenda.setForeground(new java.awt.Color(217, 2, 2));
        c_agenda.setText("Agenda");
        c_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_agendaActionPerformed(evt);
            }
        });
        consultar_Cliente.add(c_agenda);

        consultar_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        consultar_estoque.setForeground(new java.awt.Color(217, 26, 26));
        consultar_estoque.setText("Estoque");
        consultar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_estoqueActionPerformed(evt);
            }
        });
        consultar_Cliente.add(consultar_estoque);

        jMenuBar1.add(consultar_Cliente);

        jMenu5.setText("Alterar ");

        alterar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        alterar_cliente.setForeground(new java.awt.Color(152, 1, 1));
        alterar_cliente.setText("Alterar Cliente");
        alterar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_clienteActionPerformed(evt);
            }
        });
        jMenu5.add(alterar_cliente);

        agenda_servico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        agenda_servico.setForeground(new java.awt.Color(161, 0, 0));
        agenda_servico.setText("Alterar Agenda");
        agenda_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenda_servicoActionPerformed(evt);
            }
        });
        jMenu5.add(agenda_servico);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Deletar");

        deletar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        deletar_cliente.setForeground(new java.awt.Color(160, 1, 1));
        deletar_cliente.setText("Deletar Cliente");
        deletar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_clienteActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_cliente);

        deletar_agenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        deletar_agenda.setForeground(new java.awt.Color(144, 0, 0));
        deletar_agenda.setText("Deletar Servico");
        deletar_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_agendaActionPerformed(evt);
            }
        });
        jMenu6.add(deletar_agenda);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setForeground(new java.awt.Color(161, 0, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setForeground(new java.awt.Color(143, 1, 1));
        jMenuItem2.setText("Ajuda");
        jMenu3.add(jMenuItem2);

        voltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        voltar.setForeground(new java.awt.Color(161, 0, 0));
        voltar.setText("Voltar a tela de login");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jMenu3.add(voltar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 212, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comsultar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comsultar_servicoActionPerformed
        // TODO add your handling code here:
        
        
        new Consulta_Servico().setVisible(true);
        
    }//GEN-LAST:event_comsultar_servicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        
       new Cliente().setVisible(true);
        
        
        
    }//GEN-LAST:event_clienteActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        
        
        
        new Venda().setVisible(true);
        
    }//GEN-LAST:event_vendaActionPerformed

    private void consultar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_pActionPerformed
        // TODO add your handling code here:
        
        new Consultar_Produto().setVisible(true);
    }//GEN-LAST:event_consultar_pActionPerformed

    private void c_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_clienteActionPerformed
        
        new Consulta_Cliente().setVisible(true);
        
    }//GEN-LAST:event_c_clienteActionPerformed

    private void consultar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_produtoActionPerformed
        // TODO add your handling code here:
        
        new Consultar_Produto().setVisible(true);
        
    }//GEN-LAST:event_consultar_produtoActionPerformed

    private void agenda_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenda_servicoActionPerformed
        // TODO add your handling code here:
         new Alterar_Agenda().setVisible(true);
        
    }//GEN-LAST:event_agenda_servicoActionPerformed

    private void alterar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_clienteActionPerformed
        // TODO add your handling code here:
        
   
       
    }//GEN-LAST:event_alterar_clienteActionPerformed

    private void agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaActionPerformed
        // TODO add your handling code here:
        
        new Agenda().setVisible(true);
        
    }//GEN-LAST:event_agendaActionPerformed

    private void c_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_agendaActionPerformed
        // TODO add your handling code here:
        
        new Consultar_Agenda().setVisible(true);
    }//GEN-LAST:event_c_agendaActionPerformed

    private void consultar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_estoqueActionPerformed
        // TODO add your handling code here:
        new Consultar_Estoque().setVisible(true);
    }//GEN-LAST:event_consultar_estoqueActionPerformed

    private void deletar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_clienteActionPerformed
        // TODO add your handling code here:
        new Deletar_Cliente().setVisible(true);
    }//GEN-LAST:event_deletar_clienteActionPerformed

    private void deletar_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_agendaActionPerformed
        // TODO add your handling code here:
        
        new Deletar_Agenda().setVisible(true);
    }//GEN-LAST:event_deletar_agendaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:

        new Frame1().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agenda;
    private javax.swing.JMenuItem agenda_servico;
    private javax.swing.JMenuItem alterar_cliente;
    private javax.swing.JMenuItem c_agenda;
    private javax.swing.JMenuItem c_cliente;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem comsultar_servico;
    private javax.swing.JMenu consultar;
    private javax.swing.JMenu consultar_Cliente;
    private javax.swing.JMenuItem consultar_estoque;
    private javax.swing.JMenuItem consultar_p;
    private javax.swing.JMenuItem consultar_produto;
    private javax.swing.JMenuItem deletar_agenda;
    private javax.swing.JMenuItem deletar_cliente;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem venda;
    private javax.swing.JMenuItem voltar;
    // End of variables declaration//GEN-END:variables
}
